avoid IO error when using image as a base for other images
If /etc is a volume in the image, then the runtime container
is not allowed to write files into it. This leads to errors like:

    $ docker run --rm -t --entrypoint /bin/sh puppet:alpine -c "apk-install abook"
    docker run --rm -t --entrypoint /bin/sh jumanjiman/puppet:alpine -c "apk-install abook"
    fetch http://dl-4.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
    ERROR: http://dl-4.alpinelinux.org/alpine/edge/main/: IO ERROR
    WARNING: Ignoring APKINDEX.0bc0b73a.tar.gz: No such file or directory
    fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
    ERROR: http://dl-4.alpinelinux.org/alpine/edge/testing/: IO ERROR
    WARNING: Ignoring APKINDEX.b83cced8.tar.gz: No such file or directory
    ERROR: unsatisfiable constraints:
      abook (missing):
        required by: world[abook]

Therefore, do not hard-code /etc as a volume.
If somebody wants /etc as a volume,
the person can use docker `-v` to do so.